services:
  server:
    image: ghcr.io/pycabbage/its-personal-exercises:latest
    pull_policy: always
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - application_network
  db:
    image: mysql:8.4
    restart: always
    user: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    # ports:
    #   - "3306:3306/tcp"
    #   - "33060:33060/tcp"
    expose:
      - "3306/tcp"
      - "33060/tcp"
    command: |
      --default-time-zone=+09:00
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 5s
    networks:
      - application_network

volumes:
  db-data:

networks:
  application_network:
