server:
  port: 8080

logging:
  level:
    org.springframework.security: trace

spring:
  security:
#    user:
#      name: user
#      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
